import { FiBarChart2,FiBookOpen,FiCalendar,FiClipboard,FiClock,FiDroplet,FiGrid,FiHeart,FiHome,FiList,FiMap,FiPackage,FiSmile,FiTarget,FiTrendingUp,FiUsers } from 'react-icons/fi';
import type { MenuItem } from '../menuItems';

export const communityMenu: MenuItem =
  {
    id: 'community',
    label: 'Community',
    icon: FiUsers,
    children: [
      {
        id: 'registers',
        label: 'Registers',
        icon: FiList,
        path: '/registers',
        allowedRoles: ['super_admin', 'mahall', 'survey'],
        moduleKey: 'registers',
      },
      {
        id: 'survey',
        label: 'Survey & Demographics',
        icon: FiClipboard,
        path: '/survey',
        allowedRoles: ['super_admin', 'mahall', 'survey'],
        moduleKey: 'survey',
      },
      {
        id: 'locality-facilities',
        label: 'Locality Facilities',
        icon: FiMap,
        path: '/survey/facilities',
        allowedRoles: ['super_admin', 'mahall', 'survey'],
        moduleKey: 'survey',
      },
      {
        id: 'clusters',
        label: 'Clusters',
        icon: FiGrid,
        path: '/clusters',
        allowedRoles: ['super_admin', 'mahall', 'survey'],
        moduleKey: 'clusters',
      },
      {
        id: 'mosque',
        label: 'Mosque',
        icon: FiHome,
        path: '/mosque',
        allowedRoles: ['super_admin', 'mahall', 'survey', 'institute'],
        moduleKey: 'mosque',
      },
      {
        id: 'families',
        label: 'Families',
        icon: FiHome,
        path: '/families',
        allowedRoles: ['super_admin', 'mahall', 'survey'],
        moduleKey: 'families',
      },
      {
        id: 'members',
        label: 'Members',
        icon: FiUsers,
        path: '/members',
        allowedRoles: ['super_admin', 'mahall', 'survey'],
        moduleKey: 'members',
      },
      {
        id: 'committees',
        label: 'Committees',
        icon: FiUsers,
        allowedRoles: ['super_admin', 'mahall'],
        children: [
          { id: 'all-committees', label: 'All Committees', icon: FiList, path: '/committees', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'all-meetings', label: 'Meetings', icon: FiClock, path: '/committees/meetings', allowedRoles: ['super_admin', 'mahall'] },
        ],
      },
      {
        id: 'programs',
        label: 'Programs',
        icon: FiCalendar,
        path: '/programs',
        allowedRoles: ['super_admin', 'mahall'],
      },
      {
        id: 'assets',
        label: 'Asset Management',
        icon: FiPackage,
        path: '/assets',
        allowedRoles: ['super_admin', 'mahall'],
      },
      {
        id: 'development-projects',
        label: 'Development Projects',
        icon: FiTarget,
        path: '/development',
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'development',
      },
      {
        id: 'reports',
        label: 'Reports',
        icon: FiBarChart2,
        allowedRoles: ['super_admin', 'mahall', 'survey'],
        children: [
          { id: 'area', label: 'Area Report', icon: FiMap, path: '/reports/area', allowedRoles: ['super_admin', 'mahall', 'survey'] },
          { id: 'blood-bank', label: 'Blood Bank Report', icon: FiDroplet, path: '/reports/blood-bank', allowedRoles: ['super_admin', 'mahall', 'survey'] },
          { id: 'orphans', label: 'Orphans Report', icon: FiSmile, path: '/reports/orphans', allowedRoles: ['super_admin', 'mahall', 'survey'] },
          { id: 'demographics', label: 'Demographics Report', icon: FiBarChart2, path: '/reports/demographics', allowedRoles: ['super_admin', 'mahall', 'survey'] },
          { id: 'education-report-nav', label: 'Education Report', icon: FiBookOpen, path: '/education/report', allowedRoles: ['super_admin', 'mahall', 'institute'] },
          { id: 'welfare-report-nav', label: 'Welfare Report', icon: FiHeart, path: '/reports/welfare', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'community-report-nav', label: 'Community Report', icon: FiUsers, path: '/reports/community', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'annual-report-nav', label: 'Annual Report', icon: FiBarChart2, path: '/reports/annual', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'development-index-nav', label: 'Development Index', icon: FiTrendingUp, path: '/reports/development-index', allowedRoles: ['super_admin', 'mahall'] },
        ],
      },
    ],
  }
