import { FiActivity,FiAlertCircle,FiArchive,FiBarChart2,FiBell,FiBook,FiBookOpen,FiBriefcase,FiCalendar,FiCast,FiClipboard,FiCreditCard,FiDollarSign,FiDroplet,FiFile,FiFilePlus,FiFileText,FiGift,FiHeart,FiHelpCircle,FiHome,FiImage,FiLayers,FiList,FiMap,FiMessageCircle,FiMessageSquare,FiMinusCircle,FiSend,FiShare2,FiStar,FiUser,FiUserCheck,FiUsers } from 'react-icons/fi';
import type { MenuItem } from '../menuItems';

export const servicesMenu: MenuItem =
  {
    id: 'services',
    label: 'Services',
    icon: FiLayers,
    children: [
      {
        id: 'welfare',
        label: 'Welfare',
        icon: FiHeart,
        allowedRoles: ['super_admin', 'mahall', 'survey'],
        moduleKey: 'welfare',
        children: [
          {
            id: 'welfare-applications',
            label: 'Applications',
            icon: FiFileText,
            path: '/welfare/applications',
            allowedRoles: ['super_admin', 'mahall', 'survey'],
            moduleKey: 'welfare',
          },
          {
            id: 'welfare-schemes',
            label: 'Schemes',
            icon: FiGift,
            path: '/welfare/schemes',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'welfare',
          },
        ],
      },
      {
        id: 'zakat-module',
        label: 'Zakat',
        icon: FiGift,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'zakat',
        children: [
          {
            id: 'zakat-summary',
            label: 'Summary',
            icon: FiBarChart2,
            path: '/zakat',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'zakat',
          },
          {
            id: 'zakat-beneficiaries',
            label: 'Beneficiaries',
            icon: FiUsers,
            path: '/zakat/beneficiaries',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'zakat',
          },
          {
            id: 'zakat-distributions',
            label: 'Distributions',
            icon: FiSend,
            path: '/zakat/distributions',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'zakat',
          },
        ],
      },
      {
        id: 'education',
        label: 'Education',
        icon: FiBookOpen,
        allowedRoles: ['super_admin', 'mahall', 'institute'],
        moduleKey: 'education',
        children: [
          {
            id: 'education-classes',
            label: 'Classes & Students',
            icon: FiBookOpen,
            path: '/education',
            allowedRoles: ['super_admin', 'mahall', 'institute'],
            moduleKey: 'education',
          },
          {
            id: 'education-scholarships',
            label: 'Scholarships',
            icon: FiGift,
            path: '/education/scholarships',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'education',
          },
          {
            id: 'education-support',
            label: 'Academic Support',
            icon: FiHelpCircle,
            path: '/education/support',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'education',
          },
          {
            id: 'education-report',
            label: 'Education Report',
            icon: FiBarChart2,
            path: '/education/report',
            allowedRoles: ['super_admin', 'mahall', 'institute'],
            moduleKey: 'education',
          },
        ],
      },
      {
        id: 'qard-hasan',
        label: 'Qard Hasan',
        icon: FiCreditCard,
        path: '/loans',
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'loans',
      },
      {
        id: 'emergency-relief',
        label: 'Emergency Relief',
        icon: FiAlertCircle,
        path: '/relief',
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'loans',
      },
      {
        id: 'announcements',
        label: 'Announcements',
        icon: FiSend,
        path: '/announcements',
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'communication',
      },
      {
        id: 'employment',
        label: 'Employment',
        icon: FiBriefcase,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'employment',
        children: [
          {
            id: 'employers',
            label: 'Employers',
            icon: FiBriefcase,
            path: '/employment/employers',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'employment',
          },
          {
            id: 'vacancies',
            label: 'Job Vacancies',
            icon: FiFileText,
            path: '/employment/vacancies',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'employment',
          },
          {
            id: 'trainings',
            label: 'Skill Trainings',
            icon: FiBookOpen,
            path: '/employment/trainings',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'employment',
          },
          {
            id: 'job-seekers-register',
            label: 'Job Seekers Register',
            icon: FiList,
            path: '/registers/job-seekers',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'employment',
          },
        ],
      },
      {
        id: 'volunteers',
        label: 'Volunteers',
        icon: FiUserCheck,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'volunteers',
        children: [
          {
            id: 'volunteers-list',
            label: 'Volunteers',
            icon: FiUsers,
            path: '/volunteers',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'volunteers',
          },
          {
            id: 'volunteer-assignments',
            label: 'Assignments',
            icon: FiClipboard,
            path: '/volunteers/assignments',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'volunteers',
          },
        ],
      },
      {
        id: 'health',
        label: 'Health',
        icon: FiHeart,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'health',
        children: [
          {
            id: 'doctors',
            label: 'Doctors Directory',
            icon: FiUsers,
            path: '/health/doctors',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'health',
          },
          {
            id: 'blood-donors',
            label: 'Blood Donors',
            icon: FiDroplet,
            path: '/health/donors',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'health',
          },
          {
            id: 'medical-camps',
            label: 'Medical Camps',
            icon: FiClipboard,
            path: '/health/camps',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'health',
          },
          {
            id: 'palliative-cases',
            label: 'Palliative Cases',
            icon: FiAlertCircle,
            path: '/health/palliative',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'health',
            sensitiveKey: 'health',
          },
          {
            id: 'patient-support',
            label: 'Patient Support',
            icon: FiHeart,
            path: '/health/patient-support',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'health',
            sensitiveKey: 'health',
          },
        ],
      },
      {
        id: 'religious',
        label: 'Religious Services',
        icon: FiBookOpen,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'religious',
        children: [
          {
            id: 'khutbah-schedule',
            label: 'Khutbah Schedule',
            icon: FiCalendar,
            path: '/religious/khutbahs',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'religious',
          },
          {
            id: 'khateebs',
            label: 'Khateebs',
            icon: FiUsers,
            path: '/religious/khateebs',
            allowedRoles: ['super_admin', 'mahall'],
            moduleKey: 'religious',
          },
        ],
      },
      {
        id: 'counselling',
        label: 'Counselling',
        icon: FiMessageCircle,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'counselling',
        sensitiveKey: 'counselling',
        path: '/counselling',
      },
      {
        id: 'maslahat',
        label: 'Maslahat',
        icon: FiMessageSquare,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'maslahat',
        sensitiveKey: 'maslahat',
        path: '/maslahat',
      },
      {
        id: 'inheritance',
        label: 'Inheritance',
        icon: FiFile,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'inheritance',
        sensitiveKey: 'inheritance',
        path: '/inheritance',
      },
      {
        id: 'cemetery',
        label: 'Cemetery',
        icon: FiMap,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'cemetery',
        path: '/cemetery',
      },
      {
        id: 'library',
        label: 'Library',
        icon: FiBook,
        allowedRoles: ['super_admin', 'mahall'],
        moduleKey: 'library',
        children: [
          { id: 'library-books', label: 'Books', icon: FiBook, path: '/library/books', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'library-issues', label: 'Issues', icon: FiClipboard, path: '/library/issues', allowedRoles: ['super_admin', 'mahall'] },
        ],
      },
      {
        id: 'collectibles',
        label: 'Collections',
        icon: FiDollarSign,
        allowedRoles: ['super_admin', 'mahall'],
        children: [
          { id: 'varisangya', label: 'Varisangyas', icon: FiArchive, path: '/collectibles/varisangya', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'family-varisangya', label: 'Family Varisangya', icon: FiHome, path: '/collectibles/family-varisangya', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'member-varisangya', label: 'Member Varisangya', icon: FiUser, path: '/collectibles/member-varisangya', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'zakat', label: 'Zakat Collection', icon: FiGift, path: '/collectibles/zakat', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'live-dues', label: 'Live Dues', icon: FiDollarSign, path: '/collectibles/dues', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'all-collections', label: 'All Collections', icon: FiDollarSign, path: '/collections', allowedRoles: ['super_admin', 'mahall'] },
        ],
      },
      {
        id: 'registrations',
        label: 'Registrations',
        icon: FiFileText,
        allowedRoles: ['super_admin', 'mahall'],
        children: [
          { id: 'nikah', label: 'Nikah Registrations', icon: FiHeart, path: '/registrations/nikah', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'death', label: 'Death Registrations', icon: FiMinusCircle, path: '/registrations/death', allowedRoles: ['super_admin', 'mahall'] },
          {
            id: 'noc',
            label: 'NOC Services',
            icon: FiFile,
            allowedRoles: ['super_admin', 'mahall'],
            children: [
              { id: 'common-noc', label: 'Common NOC', icon: FiFileText, path: '/registrations/noc/common', allowedRoles: ['super_admin', 'mahall'] },
              { id: 'nikah-noc', label: 'Nikah NOC', icon: FiFilePlus, path: '/registrations/noc/nikah', allowedRoles: ['super_admin', 'mahall'] },
            ],
          },
          { id: 'marriage-assistance', label: 'Marriage Assistance', icon: FiHeart, path: '/registrations/marriage-assistance', allowedRoles: ['super_admin', 'mahall'] },
        ],
      },
      {
        id: 'notifications',
        label: 'Notifications',
        icon: FiBell,
        allowedRoles: ['super_admin', 'mahall'],
        children: [
          { id: 'send-notification', label: 'Send Notification', icon: FiSend, path: '/notifications/send', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'individual', label: 'Individual', icon: FiMessageSquare, path: '/notifications/individual', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'collection', label: 'Collection', icon: FiMessageCircle, path: '/notifications/collection', allowedRoles: ['super_admin', 'mahall'] },
        ],
      },
      {
        id: 'social',
        label: 'Social Media',
        icon: FiShare2,
        allowedRoles: ['super_admin', 'mahall'],
        children: [
          { id: 'banners', label: 'Banners', icon: FiImage, path: '/social/banners', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'feeds', label: 'Feeds', icon: FiCast, path: '/social/feeds', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'super-feeds', label: 'Super Feeds', icon: FiStar, path: '/social/super-feeds', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'activity-logs', label: 'Activity Logs', icon: FiActivity, path: '/social/activity-logs', allowedRoles: ['super_admin', 'mahall'] },
          { id: 'support', label: 'Support', icon: FiHelpCircle, path: '/social/support', allowedRoles: ['super_admin', 'mahall'] },
        ],
      },
    ],
  }
